### ISSUE TITLE
Retry using VS2019 or newer

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/cudasirecon-feedstock#28]
Roughly a year ago, 6d08c02b5ea97edea396c22003632c34a9a0d1d3 went back to VS2017 due to some apparent issues at the time. It would be good to remove
https://github.com/conda-forge/cudasirecon-feedstock/blob/d0229758345094a6a7738ba098fb96abfb0ae62e/recipe/conda_build_config.yaml#L1-L5

and just use the conda-forge default compilers, as cudasirecon is among the last feedstocks in conda-forge to still use VS2017.

Hopefully cudasirecon has become compatible with newer VS in the meantime (the CUDA stack has certainly made big strides in recent times)... 🤞

**Comment by tlambert03** [comment]
thank you @h-vetinari.  Sorry for being a straggler, I admit it's been a bit hard to keep this (and the `cudadecon`) recipe and the upstream libraries up to date with conda-forge.  I'm not the original author, so when changes in cuda require changes to the source code and or compilation methods, I'm slightly out of my depth and mostly just hack my way through it.  But, I'm also strapped for time like everyone else.   we dropped to vs2017  as per @jakirkham's suggestion here: https://github.com/conda-forge/cudasirecon-feedstock/pull/16#issuecomment-1573046952 

but there too, I'm just made the switch without deeply understanding why it fixed it.  not much has changed in the upstream cudasirecon library since then, so unless that was an issue in the conda-forge pipline, I suspect we may still have it now.  Which, I guess, means that we'll indeed have to dig back into the source code to keep this recipe working 😔 

perhaps I can recruit some help

**Comment by jakirkham** [comment]
Would it be possible to finish adding CUDA 12 on Windows ( https://github.com/conda-forge/cudasirecon-feedstock/pull/27 )? It looks like it needs a light touch to get it working

If so, maybe we can look at skipping older CUDA versions on Windows where legacy compilers appear to be needed here

**Comment by tlambert03** [comment]
> Would it be possible to finish adding CUDA 12 on Windows ( https://github.com/conda-forge/cudasirecon-feedstock/pull/27 )? It looks like it needs a light touch to get it working

yep! i'll try to give it a shot within the next few days

**Comment by jakirkham** [comment]
Thanks Talley! 🙏

Happy to answer questions as usual 🙂

Would add it looks like CuPy was able to move to vs2019 recently ( https://github.com/conda-forge/cupy-feedstock/pull/252 ). They dropped CUDA 11.2 and only build for CUDA 11.8 & 12.0. So it seems just dropping CUDA 11.2 may be all that is needed

**Comment by tlambert03** [comment]
thank you as always for helping out!

**Comment by h-vetinari** [comment]
Closing as fixed by #27
